name: Build on Windows

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      release:
        type: boolean

jobs:
  build_on_windows:
    name: Build on Windows Server 2022
    runs-on: windows-2022
    env:
      build_tests: ON
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependency
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install llvm cmake ninja vswhere
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
        with:
          sdk-version: 19041
      - name: Set environment variables for release
        if: ${{ inputs.release }}
        run: |
          echo "build_tests=OFF" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Build WasmEdge
        run: |
          $vsPath = (vswhere -latest -property installationPath)
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64 -winsdk=10.0.19041.0"
          $Env:CC = "clang-cl"
          $Env:CXX = "clang-cl"
          $cmake_sys_version = "10.0.19041.0"
          $llvm_dir = (llvm-config -cmakedir)
          cmake -Bbuild -GNinja "-DCMAKE_SYSTEM_VERSION=$cmake_sys_version" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded "-DWASMEDGE_BUILD_TESTS=$Env:build_tests" "-DLLVM_DIR=$llvm_dir" -DWASMEDGE_BUILD_PACKAGE="ZIP" .
          cmake --build build
      - name: Test WasmEdge
        continue-on-error: true
        run: |
          $vsPath = (vswhere -latest -property installationPath)
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64 -winsdk=10.0.19041.0"
          $Env:PATH += ";$pwd\\build\\lib\\api"
          cd build
          tools\wasmedge\wasmedge -v
          ctest
          cd -
      - name: Create WasmEdge package
        run: |
          $vsPath = (vswhere -latest -property installationPath)
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64 -winsdk=10.0.19041.0"
          cmake --build build --target package
          Get-ChildItem -Path "$pwd\\build"
